version: '3'
services:
  app:
    build: .
    ports:
      - '8080:8080'
    networks:
      - net
    depends_on:
      - db
  db:
    image: 'mongo'
    networks:
      net:
        ipv4_address: 172.16.238.10
    volumes:
      - './data/db:/data/db'
networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
